blank_issues_enabled: true
contact_links:
  - name: My issue is confidential
    url: mailto:contact.blenderdefender@gmail.com?subject=[Confidential+Issue]
    about: Your issue is confidential? Please report it here.
